<h1>
	<?PHP echo $this->translate->_('My Events'); ?>
</h1>
<p>
    <?PHP

    echo "<p>".$this->translate->_('Your events are listed below').".</p>"; ?>

    <?php
    foreach($this->messages as $message):
        echo "<div class='message'>{$message}</div>";
    endforeach;
    ?>
</p>

<table class="tablesorter" style="width: 500px;">
    <thead>
        <tr>
            <th><?PHP echo $this->translate->_('Name'); ?></th>
            <th><?PHP echo $this->translate->_('Date'); ?></th>
            <th><?PHP echo $this->translate->_('Published'); ?></th>
            <th><?PHP echo $this->translate->_('Quick links'); ?></th>
        </tr>        
    </thead>
<?PHP foreach ($this->events as $event): ?>
    <tr>
        <td><a href="<?PHP echo $this->url(array('lang' => $this->lang, 'module' => 'admin','controller' => 'event', 'action' => 'index','event_id' => $event->event_id)); ?>"><?PHP echo $event->name; ?></a></td>
        <td><?PHP echo $event->start_time; ?></td>
        <th>
            <?PHP if($event->published){ echo "<div style='color: green'>".$this->translate->_('Live'); }else{ echo "<div style='color: red;'>".$this->translate->_('Draft'); } ?></div>
        </th>
        <td><a href="<?PHP echo $this->url(array('lang' => $this->lang, 'module' => 'admin','controller' => 'event', 'action' => 'edit','event_id' => $event->event_id)); ?>"><?PHP echo $this->translate->_('Edit'); ?></a> 
            | <a href="<?PHP echo $this->url(array('lang' => $this->lang, 'module' => 'admin','controller' => 'event', 'action' => 'delete','event_id' => $event->event_id)); ?>"><?PHP echo $this->translate->_('Delete'); ?></a> 
            | <a href="<?PHP echo $this->url(array('lang' => $this->lang, 'module' => 'admin','controller' => 'event', 'action' => 'publish','event_id' => $event->event_id)); ?>"><?PHP if($event->published){ echo $this->translate->_('Unpublish'); } else{ echo $this->translate->_('Publish'); } ?></a></td>
    </tr>
<?PHP endforeach; ?>
</table>