<h1>
	<?PHP
	$eventColNames = Attend_Db_Table_Row_Event::getColumnNames('both');
	echo $this->event[$eventColNames['name']]; ?>
</h1>
<h3>
	<?PHP echo $this->translate->_('Overview'); ?>
</h3>
<p>
<?PHP echo $this->event[$eventColNames['location']]."<br/>"; ?> <?PHP echo $this->event[$eventColNames['startTime']]; ?> - <?PHP echo $this->event[$eventColNames['endTime']]."<br/>"; ?>
</p>
<h3>
	<?php echo $this->translate->_('Details'); ?>
</h3>
<div class="details" >
	<p>
		<?php echo nl2br($this->event[$eventColNames['details']]);?>
	</p>
</div>