<?PHP echo $this->translate->_('Hello'); ?>,
<br/><br/>
<?PHP echo $this->translate->_('this is an invoice from the ticket system'); ?>.
<table>
	<tbody><tr><td><h2><?PHP echo $this->ticketType; ?></h2>
	<table>
		<tbody><tr>
			<td>
				<?PHP echo $this->translate->_('Name'); ?> 
			</td>
			<td>
				<?PHP echo $this->name; ?>
            </td>
		</tr>
		<tr>
			<td>
				<?PHP echo $this->translate->_('Email'); ?> 
			</td>
			<td>
				<a href="mailto:<?PHP echo $this->email; ?>" target="_blank"><?PHP echo $this->email; ?></a>
            </td>
		</tr>
		<tr>
			<td>
				<?PHP echo $this->translate->_('Price'); ?>
			</td>
			<td>
				<?PHP echo $this->price; ?> SEK
			</td>
		</tr>
	</tbody>
</table>
<?PHP echo $this->translate->_('Pay'); ?> <?PHP echo $this->price; ?> SEK <?PHP echo $this->translate->_('along with the OCR'); ?>
: <?PHP echo $this->ocr; ?> <?PHP echo $this->translate->_('to'); ?> BankGiro XXXX-XXXX 
<?PHP echo $this->translate->_('if you want your ticket.'); ?>
<br/><br/>
<?PHP echo $this->translate->_('Greetings'); ?> TDDD27