<?php
    echo $this->doctype();
?>
<html>
<head>
    <meta  charset="UTF-8"/>
    <title>Attend</title>
    <?php 
    echo $this->headLink()->appendStylesheet('/css/global.css');
    echo $this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.8.20/themes/base/jquery-ui.css'); 
    echo $this->headLink()->appendStylesheet('http://static.jquery.com/ui/css/demo-docs-theme/ui.theme.css');   
    
    echo $this->headScript();
    ?>
</head>
<body>
    <div id="header" style=" background-color: #EEEEEE; height: 50px;">
        <div id="header-logo" style="float: left; padding-top: 8px; padding-left: 8px;">
            <h2>Attend</h2>
        </div>
        <div id="header-links" style="float: right; margin: 10px 10px 0px 0px;">
            
            <a href="<?PHP  echo $this->url(array('lang' => 'sv'),'defaultRoute'); ?>">
 
           <?PHP
           //
           // Make the current language bold
           //
            $langs = array(
                    'sv' => 'Svenska',
                    'en' => 'English'
                );

            while($value = current($langs)){
                if(key($langs) == $this->layout()->lang)
                {
                    echo "<a href=".$this->url(array('lang' => key($langs)),'defaultRoute')."><b>".$langs[key($langs)]."</b></a> ";
                }
                else
                {
                    echo "<a href=".$this->url(array('lang' => key($langs)),'defaultRoute').">".$langs[key($langs)]."</a> ";
                }
                next($langs);
            } 
            ?>
                
        </div>
    </div>
    <div id="wrapper">
            <?PHP
            if (Zend_Registry::isRegistered('topLevelMenu')) {
                $menu = Zend_Registry::get('topLevelMenu');
                echo "<div id='top-level-navigation'>".$this->navigation()->menu()->renderMenu($menu)."</div>";
            }
            ?>            
            <?PHP
            if (Zend_Registry::isRegistered('verticalMenu')) {
                $menu = Zend_Registry::get('verticalMenu');
                echo "<div id='vertical-menu'>".$this->navigation()->menu()->renderMenu($menu)."</div>";
            }
            ?>
        <div id="content">
            <?php echo $this->layout()->content ?>
        </div>
    </div>
    <div id="footer" style="background-color: #EEEEEE; height: 50px; text-align: center;">
            <div style="padding-top: 20px;">Copyright &#169; Moser & Josefsson 2012</div>
    </div>
</body>
</html>