<h1>
	<?PHP
	$eventNameCol = Attend_Db_Table_Row_Event::getColumnName('name');
	echo $this->escape($this->event[$eventNameCol]); ?>
</h1>
<h3>
    <?PHP echo $this->translate->_('Attendees'); ?>
</h3>
<br />
<table>
    <tr>
        <th>
            <?PHP echo $this->translate->_('Name'); ?>
        </th>
        <th>
            <?PHP echo $this->translate->_('LiU-ID'); ?>
        </th>
        <th>
            <?PHP echo $this->translate->_('Email'); ?>
        </th>
        <th>
            <?PHP echo $this->translate->_('Ticket'); ?>
        </th>
        <th>
            <?PHP echo $this->translate->_('Payment'); ?>
        </th>
        <th>
            <?PHP echo $this->translate->_('OCR'); ?>
        </th>
    </tr>
<?PHP
foreach ($this->attendees as $att):
?>
    <tr>
        <td>
            <?PHP echo $this->escape($att['attendee_name']); ?>
        </td>
        <td>
            <?PHP echo $this->escape($att['liu_id']); ?>
        </td>
        <td>
            <?PHP echo $this->escape($att['email']); ?>
        </td>
        <td>
            <?PHP echo $this->escape($att['ticket_type_name']); ?>
        </td>
        <td>
            <?PHP
			
			if($this->escape($att['payment']))
			{
				echo $this->translate->_('Cash');
			}
			else
			{
				echo $this->translate->_('Invoice');
			}
			
			?>
        </td>
        <td>
            <?PHP echo "";//$att->ocr; ?>
        </td>
    </tr>
<?PHP
endforeach;
?>
</table>